boilerplate with Remix, Chakra-UI, Visx
mattesats/btc-discount-web-client pull request #5
Opened 2022-02-18 08:03 UTC by SiriusLL

☕️

2022-02-21 22:35 UTC, mattesats requested changes
Looks good! Just a couple questions. @SiriusLL

2022-02-21 22:35 UTC, mattesats commented on app/root.tsx
> +
It's always a good practice to remove commented code or code that isn't being used.

2022-02-21 22:35 UTC, mattesats commented on remix.config.js
> +  // devServerPort: 8002
Can you explain why this is commented? These kinda look like the default options...

2022-02-22 11:59 UTC, SiriusLL commented on app/root.tsx
> +
Check

2022-02-22 13:13 UTC, SiriusLL commented on remix.config.js
> +  // devServerPort: 8002
These are commented by default, I could not find much information as to why.

2022-02-23 17:37 UTC, aquanow-greg commented on remix.config.js
> +  // devServerPort: 8002
Ok. You can just remove these lines then.

2022-02-24 03:17 UTC, mattesats approved these changes

2022-02-24 03:19 UTC, merged

2022-02-28 17:40 UTC, mattesats commented
Closes #3